apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-qrrh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-qrrh
    app.kubernetes.io/part-of: jvm-build-suite-application-eghf
  name: jvm-build-suite-component-qrrh
  namespace: jvm-build-zigp-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jvm-build-suite-component-qrrh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jvm-build-suite-component-qrrh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:895dfd11ef23388af582e757d247b447d21f1ea6e039bc17b5362db91c0f4905
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
